import Axios from 'axios';
import NavAdmin from '@/components/NavAdmin';
import UserAction from '@/components/UserAction';
import Head from 'next/head';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import MenuUsers from '@/components/MenuUsers';

export default function Users() {

  const API_URL = "http://localhost:8080/api/user";
  
  const [users, setUsers] = useState([]); 
  const [filteredUsers, setFilteredUsers] = useState([]); 
  const [searchName, setSearchName] = useState(""); 
  const [searchId, setSearchId] = useState(""); 

  useEffect(() => {
    const getAllUsers = async () => {
      try {
        const response = await Axios.get(API_URL);
        setUsers(response.data);
        setFilteredUsers(response.data); 
      } catch (error) {
        console.error('Erro ao buscar os usuários:', error);
      }
    };

    getAllUsers();
  }, []);

  const handleSearchByName = (event) => {
    const value = event.target.value;
    setSearchName(value);

    const filtered = users.filter(user => 
      user.name.toLowerCase().includes(value.toLowerCase())
    );
    setFilteredUsers(filtered);
  };

  const handleSearchById = (event) => {
    const value = event.target.value;
    setSearchId(value);

    const filtered = users.filter(user => 
      user._id.includes(value)
    );
    setFilteredUsers(filtered);
  };

  return (
    <>
      <Head>
        <title>APP-BC</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div>
        <NavAdmin />
        <MenuUsers />
      </div>

      <div className="d-flex justify-content-center p-2">
        <div className="container">
          <div className="row border-bottom">
            <h3 className="text-center w-100 fw-bold">LISTAGEM DE USUÁRIOS CADASTRADOS</h3>
            <div className="d-flex justify-content-center align-items-center" style={{ width: '100%' }}>
              <div className="d-flex gap-3" style={{ width: '100%', maxWidth: '1000px' }}>
                {/* Primeira barra de pesquisa */}
                <div className="input-group search-container" style={{ flex: 1 }}>
                  <input 
                    type="text" 
                    className="form-control search-input" 
                    style={{ maxWidth: '450px', width: '100%', fontSize: '0.9rem', height: '40px' }} 
                    placeholder="Busca por Nome"
                    value={searchName}
                    onChange={handleSearchByName}
                  />
                  <div className="input-group-append" style={{ cursor: 'pointer' }}>
                    <span 
                      className="input-group-text" 
                      style={{
                        height: '40px',
                        display: 'flex',
                        alignItems: 'center',
                        justifyContent: 'center',
                        borderRadius: '0',
                        padding: '0 10px',
                        cursor: 'pointer'
                      }}>
                      <i className="fas fa-search" style={{ fontSize: '1rem' }}></i>
                    </span>
                  </div>
                </div>

                {/* Segunda barra de pesquisa */}
                <div className="input-group search-container" style={{ flex: 1 }}>
                  <input 
                    type="text" 
                    className="form-control search-input" 
                    style={{ maxWidth: '450px', width: '100%', fontSize: '0.9rem', height: '40px' }} 
                    placeholder="Busca por ID"
                    value={searchId}
                    onChange={handleSearchById}
                  />
                  <div className="input-group-append" style={{ cursor: 'pointer' }}>
                    <span 
                      className="input-group-text" 
                      style={{
                        height: '40px',
                        display: 'flex',
                        alignItems: 'center',
                        justifyContent: 'center',
                        borderRadius: '0',
                        padding: '0 10px',
                        cursor: 'pointer'
                      }}>
                      <i className="fas fa-search" style={{ fontSize: '1rem' }}></i>
                    </span>
                  </div>
                </div>
              </div>
            </div>

            <table className="table table-hover">
              <thead>
                <tr>
                  <th scope="col" className="text-center">ID</th>
                  <th scope="col" className="text-center">Nome</th>
                  <th scope="col" className="text-center">E-mail</th>
                  <th scope="col" className="text-center">Ação</th>
                </tr>
              </thead>
              <tbody>
                {filteredUsers.map(user => (
                  <tr key={user._id}>
                    <th scope="row" className="text-center">{user._id}</th> 
                    <td className="text-center">{user.name}</td> 
                    <td className="text-center">{user.email}</td> 
                    <td className="text-center">
                      <UserAction pid={user._id}></UserAction> 
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </>
  );
}
