import NavAdmin from '@/components/NavAdmin'
import MenuUsers from '@/components/MenuUsers';
import Head from 'next/head'
import Link from 'next/link'
import { useEffect, useState } from 'react';
import Axios from 'axios';
import { useRouter } from 'next/router';

export default function updateUser() {
  
  const API_URL = "http://localhost:8080/api/user/"

  const [user, setUser] = useState({
    id: "",
    name: "",
    email: "",
    user: "",
    pwd: "",
    level: "",
    status: "",
    //create_date: ""
  });

  const router = useRouter();
  const [pid] = useState(router.query.pid);

  const [message, setMensage] = useState({ message:"", status:""});

  const optionsLevel = [
    {value: '', text: '-- Selecione um nível de acesso --'},
    {value: 'admin', text: 'Administrador'},
    {value: 'user', text: 'Usuário'},
    {value: 'reader', text: 'Leitor'},
  ];

  const optionsStatus = [
    {value: '', text: '-- Selecione um estado --'},
    {value: 'true', text: 'Ativo'},
    {value: 'false', text: 'Inativo'},
  ];

     useEffect(() => {
        const getUser = async () => {
          try {
            const response = await Axios.get(API_URL + pid);
            setMensage( { message: "Usuário encontrado" , status: "ok"} ); 
            setUser( response.data.foundedUser );
          } catch (error) {
            console.error('Erro ao buscar os usuários:', error);
            setMensage( { message: "Erro ao buscar os Usuários!", status: "error"} );
          }
        };
    
        getUser();
      }, []);
      
      const handleChange = (event) => {
        const { name, value } = event.target;
        setUser({
          ...user,
          [name]: value
        });
      };

      const handleUpdateUser = async () => {
        try {
          const response = await Axios.put(API_URL + pid, user);
          setMensage( { message: "Usuário editado com sucesso!" , status: "ok"} );      
        } catch (error) {
          console.error('Erro ao alterar o Usuário:', error);
          setMensage( { message: "Erro ao alterar o Usuário!", status: "error"} );
        }
      };

  return (
    <>
      <Head>
        <title>APP-BC</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div>
        <NavAdmin />
        <MenuUsers />
        { 
          message.status==="" ? "" : 
          message.status==="ok" ? <div className='alert alert-success' role='alert'> { message.message } <Link className='alert-link' href='/admin/users'>Voltar</Link></div> : 
          <div className='alert alert-danger' role='alert'> { message.message } <Link className='alert-link' href='/admin/users'>Voltar</Link></div>
        }
      </div>
  
      <div className="d-flex justify-content-center p-2">
        <div className="container">
            <div className="row border-bottom fw-bold">
                <h3 className="text-center fw-bold"> EDITAR USUÁRIO </h3>
            
                <form method="POST">
                <div className="form-group">
                    <label className="form-label mt-2 mb-0" htmlFor="name">Nome</label>
                    <input type="text" id="name" name="name" className="form-control" value={user.name} onChange={handleChange}/>
                </div>
                <div className="form-group">
                    <label className="form-label mt-2 mb-0" htmlFor="email">E-mail</label>
                    <input type="text" id="email" name="email" className="form-control" value={user.email} onChange={handleChange} />
                </div>
                <div className="form-group">
                    <label className="form-label mt-2 mb-0" htmlFor="user">Usuário</label>
                    <input type="text" id="user" name="user" className="form-control" value={user.user} onChange={handleChange} />
                </div>
                <div className="form-group">
                    <label className="form-label mt-2 mb-0" htmlFor="pwd">Senha</label>
                    <input type="password" id="pwd" name="pwd" className="form-control" value={user.pwd} onChange={handleChange} />
                </div>
                <div className="form-group">
                    <label className="form-label mt-2 mb-0" htmlFor="level">Nível</label>
                    <select className="form-select" id="level" name="level" value={user.level} onChange={handleChange}>
                      {optionsLevel.map(option => (
                        <option key={option.value} value={option.value}>
                          {option.text}
                        </option>
                      ))}
                    </select>
                </div>
                <div className="form-group">
                    <label className="form-label mt-2 mb-0" htmlFor="status">Status</label>
                    <select className="form-select" id="status" name="status" value={user.status} onChange={handleChange}>
                      {optionsStatus.map(option => (
                        <option key={option.value} value={option.value}>
                          {option.text}
                        </option>
                      ))}
                    </select>
                </div>
                {/*<div className="form-group">
                    <label className="form-label mt-2 mb-0" htmlFor="create_date">Data de Criação</label>
                    <input type="text" id="create_date" name="create_date" className="form-control" value={ user.create_date } readOnly/>
                </div>*/}
                <div className="form-group p-2">
                    <button className="btn btn-success fw-bold mx-1" type="button" onClick={handleUpdateUser} >SALVAR</button>
                    <Link className="btn btn-secondary fw-bold mx-1" href="/admin/users">VOLTAR</Link>
                </div>
                </form>
            </div>
        </div>
      </div>  
  </>
  )
}


