import NavAdmin from '@/components/NavAdmin'
import MenuUsers from '@/components/MenuUsers';
import Head from 'next/head'
import Link from 'next/link'
import { useEffect, useState } from 'react';
import Axios from 'axios';
import { useRouter } from 'next/router';

export default function deleteEvent() {
  
  const API_URL = "http://localhost:8080/api/event"

  const [event, setEvent] = useState({
    id: "",
    name: "",
    description: "",
    comments: "",
    date: "",
    //create_date: ""
  });

  const router = useRouter();
  const [pid] = useState(router.query.pid);

  const [message, setMensage] = useState({ message:"", status:""});


  useEffect(() => {
    if (!pid) return; 

    const getEvent = async () => {
        try {
            const response = await Axios.get(`${API_URL}/${pid}`);
            const fetchedEvent = response.data.foundedEvent;

            const formattedDate = fetchedEvent.date ? fetchedEvent.date.replace(" ", "T") : ""; 
            setEvent({
                ...fetchedEvent,
                date: formattedDate, 
            });

            setMensage({ message: response.data.message, status: "ok" });
        } catch (error) {
            console.error("Erro ao buscar o evento:", error);
            setMensage({ message: "Erro ao buscar o Evento!", status: "error" });
        }
    };

    getEvent();
  }, [pid]); 

  const handleDeleteEvent = async () => {
    try {
      const response = await Axios.delete(`${API_URL}/${pid}`); 
      setMensage({ message: response.data.msg, status: "ok" });
      router.push('/admin/events'); 
    } catch (error) {
      console.error("Erro ao deletar o Evento:", error);
      setMensage({ message: "Erro ao deletar o Evento!", status: "error" });
    }
  };

  function formatDateTimeForInput(isoDate) {
        
    return isoDate;
}

  return (
    <>
      <Head>
        <title>APP-BC</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div>
        <NavAdmin />
        <MenuUsers />
        { 
          message.status==="" ? "" : 
          message.status==="ok" ? <div className='alert alert-success' role='alert'> { message.message } <Link className='alert-link' href='/admin/events'>Voltar</Link></div> : 
          <div className='alert alert-danger' role='alert'> { message.message } <Link className='alert-link' href='/admin/events'>Voltar</Link></div>
        }
      </div>
  
      <div className="d-flex justify-content-center p-2">
        <div className="container">
            <div className="row border-bottom fw-bold">
                <h3 className="text-center fw-bold"> DELETAR EVENTO </h3>
            
                <form method="POST">
                <div className="form-group">
                    <label className="form-label mt-2 mb-0" htmlFor="name">Nome</label>
                    <input type="text" id="name" name="name" className="form-control" value={event.name} readOnly/>
                </div>
                <div className="form-group">
                    <label className="form-label mt-2 mb-0" htmlFor="description">Descrição</label>
                    <input type="text" id="description" name="description" className="form-control" value={event.description} readOnly />
                </div>
                <div className="form-group">
                    <label className="form-label mt-2 mb-0" htmlFor="comments">Comentários</label>
                    <input type="text" id="comments" name="comments" className="form-control" value={event.comments} readOnly />
                </div>
                <div className="form-group">
                    <label className="form-label mt-2 mb-0" htmlFor="date">Data</label>
                    <input type="datetime-local" id="date" name="date" className="form-control" value={formatDateTimeForInput(event.date)} readOnly />
                </div>
                {/*<div className="form-group">
                    <label className="form-label mt-2 mb-0" htmlFor="create_date">Data de Criação</label>
                    <input type="text" id="create_date" name="create_date" className="form-control" value={ event.create_date } readOnly/>
                </div>*/}
                <div className="form-group p-2">
                    <button className="btn btn-danger fw-bold mx-1" type="button" onClick={handleDeleteEvent} >DELETAR</button>
                    <Link className="btn btn-secondary fw-bold mx-1" href="/admin/events">VOLTAR</Link>
                </div>
                </form>
            </div>
        </div>
      </div>  
  </>
  )
}


