import NavAdmin from '@/components/NavAdmin'
import MenuUsers from '@/components/MenuUsers';
import Head from 'next/head'
import Link from 'next/link'
import { useState } from 'react';
import Axios from 'axios';

export default function handleCreateEvent() {
  
    const API_URL = "http://localhost:8080/api/event/"

    const [event, setEvent] = useState({
        id: "",
        name: "",
        description: "",
        comments: "",
        date: "",
        //create_date: ""
      });

  const [message, setMensage] = useState({ message:"", status:""});

  const handleChange = (e) => {
    const { name, value } = e.target; 
    setEvent((prevEvent) => ({
      ...prevEvent, 
      [name]: value 
    }));
  };
  

  const handleCreateEvent = async () => {
    try {
      const response = await Axios.post(API_URL, event);
      setMensage( { message: "Evento Cadastrado!" , status: "ok"} );      
    } catch (error) {
      console.error('Erro ao criar o Evento:', error);
      setMensage( { message: "Erro ao criar o Evento!", status: "error"} );
    }
  };

  return (
    <>
      <Head>
        <title>APP-BC</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div>
        <NavAdmin />
        <MenuUsers />
        { 
          message.status==="" ? "" : 
          message.status==="ok" ? <div className='alert alert-success' role='alert'> { message.message } <Link className='alert-link' href='/admin/events'>Voltar</Link></div> : 
          <div className='alert alert-danger' role='alert'> { message.message } <Link className='alert-link' href='/admin/events'>Voltar</Link></div>
        }
      </div>
  
      <div className="d-flex justify-content-center p-2">
        <div className="container">
            <div className="row border-bottom fw-bold">
                <h3 className='fw-bold text-center'> CADASTRO DE EVENTO </h3>
            
              <form method="POST">
              <div className="form-group">
                    <label className="form-label mt-2 mb-0" htmlFor="name">Nome</label>
                    <input type="text" id="name" name="name" className="form-control" value={event.name} onChange={handleChange}/>
                </div>
                <div className="form-group">
                    <label className="form-label mt-2 mb-0" htmlFor="description">Descrição</label>
                    <input type="text" id="description" name="description" className="form-control" value={event.description} onChange={handleChange} />
                </div>
                <div className="form-group">
                    <label className="form-label mt-2 mb-0" htmlFor="comments">Comentários</label>
                    <input type="text" id="comments" name="comments" className="form-control" value={event.comments} onChange={handleChange} />
                </div>
                <div className="form-group">
                    <label className="form-label mt-2 mb-0" htmlFor="date">Data</label>
                    <input type="datetime-local" id="date" name="date" className="form-control" value={event.date} onChange={handleChange} />
                </div>
                <div className="form-group p-2">
                    <button className="btn btn-success mx-1 fw-bold" type="button" onClick={handleCreateEvent} >SALVAR</button>
                    <Link className="btn btn-secondary text-white mx-1 fw-bold" href="/admin">VOLTAR</Link>
                </div>
                </form>
            </div>
            </div>
            </div>
  </>
  )
}


