import Axios from 'axios';
import NavAdmin from '@/components/NavAdmin';
import EventAction from '@/components/EventAction';
import Head from 'next/head';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import MenuUsers from '@/components/MenuUsers';

export default function Events() {

  const API_URL = "http://localhost:8080/api/event";
  
  const [events, setEvents] = useState([]); 
  const [filteredEvents, setFilteredEvents] = useState([]); 
  const [searchId, setSearchId] = useState(""); 
  const [startDate, setStartDate] = useState(""); 
  const [endDate, setEndDate] = useState(""); 

  useEffect(() => {
    const getAllEvents = async () => {
      try {
        const response = await Axios.get(API_URL);
        setEvents(response.data.events);
        setFilteredEvents(response.data.events); 
      } catch (error) {
        console.error('Erro ao buscar os Eventos:', error);
      }
    };

    getAllEvents();
  }, []);

  const handleSearchByDate = () => {
    if (!startDate || !endDate) {
      alert('Por favor, preencha ambas as datas para buscar.');
      return;
    }
  
    const start = new Date(`${startDate}T00:00:00`).toISOString(); 
    const end = new Date(`${endDate}T23:59:59`).toISOString();     
  
    if (new Date(start) > new Date(end)) {
      alert('A data inicial não pode ser maior que a data final.');
      return;
    }
  
    Axios.get(`${API_URL}/dateInterval/date-range`, {
      params: { startDate: start, endDate: end }
    })
      .then(response => {
        setFilteredEvents(response.data);
      })
      .catch(error => {
        console.error('Erro ao buscar eventos por intervalo de datas:', error);
        alert('Erro ao buscar eventos. Verifique o console para mais detalhes.');
      });
  };

  const handleSearchById = (event) => {
    const value = event.target.value;
    setSearchId(value);

    const filtered = events.filter(event => 
      event._id.includes(value)
    );
    setFilteredEvents(filtered);
  };

  return (
    <>
      <Head>
        <title>APP-BC</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div>
        <NavAdmin />
        <MenuUsers />
      </div>

      <div className="d-flex justify-content-center p-2">
        <div className="container">
          <div className="row border-bottom">
            <h3 className="text-center w-100 fw-bold">LISTAGEM DE EVENTOS CADASTRADOS</h3> 
            <div className="d-flex justify-content-center align-items-center" style={{ width: '100%' }}>
              <div className="d-flex gap-3" style={{ width: '100%', maxWidth: '1000px' }}>
                
                <div className="input-group search-container" style={{ flex: 1 }}>
                  <input
                    type="text"
                    className="form-control search-input"
                    style={{
                      maxWidth: '450px',
                      width: '100%',
                      fontSize: '0.9rem',
                      height: '40px',
                    }}
                    placeholder="Busca por ID"
                    value={searchId}
                    onChange={handleSearchById}
                  />

                  <div className="input-group-append" style={{ cursor: 'pointer' }}>
                    <span
                      className="input-group-text"
                      style={{
                        height: '40px',
                        display: 'flex',
                        alignItems: 'center',
                        justifyContent: 'center',
                        borderRadius: '0',
                        padding: '0 10px',
                        cursor: 'pointer',
                      }}
                    >
                      <i className="fas fa-search" style={{ fontSize: '1rem' }}></i>
                    </span>
                  </div>
                </div>
                
                <div className="input-group search-container" style={{ flex: 1 }}>
                  <div style={{ display: 'flex', gap: '10px', alignItems: 'center', width: '100%' }}>
                    <input
                      type="date"
                      className="form-control search-input"
                      style={{
                        fontSize: '0.9rem',
                        height: '40px',
                        width: '100%',
                      }}
                      value={startDate}
                      onChange={(e) => setStartDate(e.target.value)}
                    />
                  
                    <input
                      type="date"
                      className="form-control search-input"
                      style={{
                        fontSize: '0.9rem',
                        height: '40px',
                        width: '100%',
                      }}
                      value={endDate}
                      onChange={(e) => setEndDate(e.target.value)}
                    />

                    <div className="input-group-append" style={{ cursor: 'pointer' }}>
                      <span
                        className="input-group-text"
                        style={{
                          height: '40px',
                          display: 'flex',
                          alignItems: 'center',
                          justifyContent: 'center',
                          borderRadius: '0',
                          padding: '0 10px',
                          cursor: 'pointer',
                        }}
                        onClick={handleSearchByDate}
                      >
                        <i className="fas fa-search" style={{ fontSize: '1rem' }}></i>
                      </span>
                    </div>
                  </div>
                </div>
              </div>
            </div>

            <table className="table table-hover">
              <thead>
                <tr>
                  <th scope="col" className="text-center">ID</th>
                  <th scope="col" className="text-center">Nome</th>
                  <th scope="col" className="text-center">Descrição</th>
                  <th scope="col" className="text-center">Data</th>
                  <th scope="col" className="text-center">Ação</th>
                </tr>
              </thead>
              <tbody>
                {filteredEvents.map(event => (
                  <tr key={event._id}>
                    <th scope="row" className="text-center">{event._id}</th> 
                    <td className="text-center">{event.name}</td> 
                    <td className="text-center">{event.description}</td> 
                    <td className="text-center">{event.date}</td> 
                    <td className="text-center">
                      <EventAction pid={event._id}></EventAction> 
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </>
  );
}
