import NavAdmin from '@/components/NavAdmin'
import MenuUsers from '@/components/MenuUsers';
import Head from 'next/head'
import Link from 'next/link'
import { useEffect, useState } from 'react';
import Axios from 'axios';
import { useRouter } from 'next/router';

export default function deleteProfessional() {
  
  const API_URL = "http://localhost:8080/api/professional"

  const [professional, setProfessional] = useState({
    id: "",
    name: "",
    specialty: "",
    contact: "",
    phone_number: "",
    status: ""
    //create_date: ""
  });

  const router = useRouter();
  const [pid] = useState(router.query.pid);

  const [message, setMensage] = useState({ message:"", status:""});

  const optionsStatus = [
    {value: '', text: '-- Selecione um estado --'},
    {value: 'true', text: 'Ativo'},
    {value: 'false', text: 'Inativo'},
  ];

    useEffect(() => {
      if (!pid) return; 

      const getProfessional = async () => {
      try {
          const response = await Axios.get(`${API_URL}/${pid}`); 
          setMensage({ message: "Profissional encontrado", status: "ok" }); 
          setProfessional(response.data.foundedProfessional);
      } catch (error) {
          console.error("Erro ao buscar o profissional:", error);
          setMensage({ message: "Erro ao buscar o Profissional!", status: "error" });
      }
    };

    getProfessional();
    }, [pid]); 

    const handleDeleteProfessional = async () => {
       try {
      const response = await Axios.delete(`${API_URL}/${pid}`); 
      setMensage({ message: response.data.msg, status: "ok" });
      router.push('/admin/professionals'); 
    } catch (error) {
      console.error("Erro ao deletar o Profissional:", error);
      setMensage({ message: "Erro ao deletar o Profissional!", status: "error" });
    }
  };

  return (
    <>
      <Head>
        <title>APP-BC</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div>
        <NavAdmin />
        <MenuUsers />
        { 
          message.status==="" ? "" : 
          message.status==="ok" ? <div className='alert alert-success' role='alert'> { message.message } <Link className='alert-link' href='/admin/professionals'>Voltar</Link></div> : 
          <div className='alert alert-danger' role='alert'> { message.message } <Link className='alert-link' href='/admin/professionals'>Voltar</Link></div>
        }
      </div>
  
      <div className="d-flex justify-content-center p-2">
        <div className="container">
            <div className="row border-bottom fw-bold">
                <h3 className="text-center fw-bold"> DELETAR PROFISSIONAL </h3>
            
                <form method="POST">
                <div className="form-group">
                    <label className="form-label mt-2 mb-0" htmlFor="name">Nome</label>
                    <input type="text" id="name" name="name" className="form-control" value={professional.name} readOnly/>
                </div>
                <div className="form-group">
                    <label className="form-label mt-2 mb-0" htmlFor="specialty">Especialidade</label>
                    <input type="text" id="specialty" name="specialty" className="form-control" value={professional.specialty} readOnly />
                </div>
                <div className="form-group">
                    <label className="form-label mt-2 mb-0" htmlFor="contact">Contato</label>
                    <input type="text" id="contact" name="contact" className="form-control" value={professional.contact} readOnly />
                </div>
                <div className="form-group">
                    <label className="form-label mt-2 mb-0" htmlFor="phone_number">Número de Telefone</label>
                    <input type="text" id="phone_number" name="phone_number" className="form-control" value={professional.phone_number} readOnly />
                </div>
                <div className="form-group">
                    <label className="form-label mt-2 mb-0" htmlFor="status">Status</label>
                    <select className="form-select" id="status" name="status" value={professional.status} readOnly>
                      {optionsStatus.map(option => (
                        <option key={option.value} value={option.value}>
                          {option.text}
                        </option>
                      ))}
                    </select>
                </div>
                {/*<div className="form-group">
                    <label className="form-label mt-2 mb-0" htmlFor="create_date">Data de Criação</label>
                    <input type="text" id="create_date" name="create_date" className="form-control" value={ teacher.create_date } readOnly/>
                </div>*/}
                <div className="form-group p-2">
                    <button className="btn btn-danger fw-bold mx-1" type="button" onClick={handleDeleteProfessional} >DELETAR</button>
                    <Link className="btn btn-secondary fw-bold mx-1" href="/admin/professionals">VOLTAR</Link>
                </div>
                </form>
            </div>
        </div>
      </div>  
  </>
  )
}


