import NavAdmin from '@/components/NavAdmin'
import MenuUsers from '@/components/MenuUsers';
import Head from 'next/head'
import Link from 'next/link'
import { useState } from 'react';
import Axios from 'axios';

export default function handleCreateProfessional() {
  
    const API_URL = "http://localhost:8080/api/professional/"

    const [professional, setProfessional] = useState({
      id: "",
      name: "",
      specialty: "",
      contact: "",
      phone_number: "",
      status: ""
      //create_date: ""
    });

  const [message, setMensage] = useState({ message:"", status:""});

  const optionsStatus = [
    {value: '', text: '-- Selecione um estado --'},
    {value: 'true', text: 'Ativo'},
    {value: 'false', text: 'Inativo'},
  ];

  const handleChange = (event) => {
    const { name, value } = event.target;
    setProfessional({
      ...professional,
      [name]: value
    });
  };

  const handleCreateProfessional = async () => {
    try {
      const response = await Axios.post(API_URL, professional);
      setMensage( { message: "Profissional Cadastrado!" , status: "ok"} );      
    } catch (error) {
      console.error('Erro ao criar o Profissional:', error);
      setMensage( { message: "Erro ao criar o Profissional!", status: "error"} );
    }
  };

  return (
    <>
      <Head>
        <title>APP-BC</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div>
        <NavAdmin />
        <MenuUsers />
        { 
          message.status==="" ? "" : 
          message.status==="ok" ? <div className='alert alert-success' role='alert'> { message.message } <Link className='alert-link' href='/admin/professionals'>Voltar</Link></div> : 
          <div className='alert alert-danger' role='alert'> { message.message } <Link className='alert-link' href='/admin/professionals'>Voltar</Link></div>
        }
      </div>
  
      <div className="d-flex justify-content-center p-2">
        <div className="container">
            <div className="row border-bottom fw-bold">
                <h3 className='fw-bold text-center'> CADASTRO DE PROFISSIONAL </h3>
            
              <form method="POST">
              <div className="form-group">
                    <label className="form-label mt-2 mb-0" htmlFor="name">Nome</label>
                    <input type="text" id="name" name="name" className="form-control" value={professional.name} onChange={handleChange}/>
                </div>
                <div className="form-group">
                    <label className="form-label mt-2 mb-0" htmlFor="specialty">Especialidade</label>
                    <input type="text" id="specialty" name="specialty" className="form-control" value={professional.specialty} onChange={handleChange} />
                </div>
                <div className="form-group">
                    <label className="form-label mt-2 mb-0" htmlFor="contact">Contato</label>
                    <input type="text" id="contact" name="contact" className="form-control" value={professional.contact} onChange={handleChange} />
                </div>
                <div className="form-group">
                    <label className="form-label mt-2 mb-0" htmlFor="phone_number">Número de Telefone</label>
                    <input type="text" id="phone_number" name="phone_number" className="form-control" value={professional.phone_number} onChange={handleChange} />
                </div>
                <div className="form-group">
                    <label className="form-label mt-2 mb-0" htmlFor="status">Status</label>
                    <select className="form-select" id="status" name="status" value={professional.status} onChange={handleChange}>
                      {optionsStatus.map(option => (
                        <option key={option.value} value={option.value}>
                          {option.text}
                        </option>
                      ))}
                    </select>
                </div>
                <div className="form-group p-2">
                    <button className="btn btn-success mx-1 fw-bold" type="button" onClick={handleCreateProfessional} >SALVAR</button>
                    <Link className="btn btn-secondary text-white mx-1 fw-bold" href="/admin">VOLTAR</Link>
                </div>
                </form>
            </div>
          </div>
        </div>
  </>
  )
}


