import MenuAdmin from '@/components/MenuAdmin'
import NavAdmin from '@/components/NavAdmin'
import Head from 'next/head'
import Link from 'next/link'
import { useEffect } from 'react'
import { useRouter } from 'next/router'

export default function Admin() {
  const router = useRouter()

  useEffect(() => {
    // Verifica se o token está presente no localStorage
    const token = localStorage.getItem('authToken')

    // Se o token não existir ou for inválido, redireciona para a página de login
    if (!token) {
      router.push('/') // Redireciona para a página de login
    }
  }, [router]) // O useEffect será executado sempre que a página for carregada

  return (
    <>
      <Head>
        <title>APP-BC</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css"
          rel="stylesheet"
        />
      </Head>
      <div
        className="d-flex flex-column"
        style={{ minHeight: '100vh', paddingBottom: '50px' }} // Espaço para o rodapé
      >
        <NavAdmin />
        <MenuAdmin />

        {/* Conteúdo principal com flex-grow */}
        <div className="container-fluid flex-grow-1 d-flex flex-column">
          {/* Seção de Usuários */}
          <div className="row border-bottom mb-3 flex-grow-1 d-flex align-items-center">
            <div className="col d-flex align-items-center">
              <i className="fas fa-users p-1" style={{ marginRight: '10px' }}></i>
              <h3>Usuários</h3>
            </div>
            <div className="col d-flex justify-content-end">
              <div className="p-2">
                <Link className="btn btn-success btn-sm fw-bold mx-2" href="/admin/users/create">NOVO CADASTRO</Link>
              </div>
            </div>
          </div>

          {/* Seção de Estudantes */}
          <div className="row border-bottom mb-3 flex-grow-1 d-flex align-items-center">
            <div className="col d-flex align-items-center">
              <i className="fas fa-graduation-cap p-1" style={{ marginRight: '10px' }}></i>
              <h3>Estudantes</h3>
            </div>
            <div className="col d-flex justify-content-end">
              <div className="p-2">
                <Link className="btn btn-success btn-sm fw-bold mx-2" href="/admin/students/create">NOVO CADASTRO</Link>
              </div>
            </div>
          </div>

          {/* Seção de Professores */}
          <div className="row border-bottom mb-3 flex-grow-1 d-flex align-items-center">
            <div className="col d-flex align-items-center">
              <i className="fas fa-chalkboard-teacher p-1" style={{ marginRight: '10px' }}></i>
              <h3>Professores</h3>
            </div>
            <div className="col d-flex justify-content-end">
              <div className="p-2">
                <Link className="btn btn-success btn-sm fw-bold mx-2" href="/admin/teachers/create">NOVO CADASTRO</Link>
              </div>
            </div>
          </div>

          {/* Seção de Agendamentos */}
          <div className="row border-bottom mb-3 flex-grow-1 d-flex align-items-center">
            <div className="col d-flex align-items-center">
              <i className="fas fa-calendar-check p-2" style={{ marginRight: '10px' }}></i>
              <h3>Agendamentos</h3>
            </div>
            <div className="col d-flex justify-content-end">
              <div className="p-2">
                <Link className="btn btn-success btn-sm fw-bold mx-2" href="/admin/appointments/create">NOVO CADASTRO</Link>
              </div>
            </div>
          </div>

          {/* Seção de Profissionais */}
          <div className="row border-bottom mb-3 flex-grow-1 d-flex align-items-center">
            <div className="col d-flex align-items-center">
              <i className="fas fa-users-cog p-1" style={{ marginRight: '10px' }}></i>
              <h3>Profissionais</h3>
            </div>
            <div className="col d-flex justify-content-end">
              <div className="p-2">
                <Link className="btn btn-success btn-sm fw-bold mx-2" href="/admin/professionals/create">NOVO CADASTRO</Link>
              </div>
            </div>
          </div>

          {/* Seção de Eventos */}
          <div className="row border-bottom mb-3 flex-grow-1 d-flex align-items-center">
            <div className="col d-flex align-items-center">
              <i className="fas fa-calendar-alt p-2" style={{ marginRight: '10px' }}></i>
              <h3>Eventos</h3>
            </div>
            <div className="col d-flex justify-content-end">
              <div className="p-2">
                <Link className="btn btn-success btn-sm fw-bold mx-2" href="/admin/events/create">NOVO CADASTRO</Link>
              </div>
            </div>
          </div>
        </div>

        {/* Rodapé fixo */}
        <footer className="bg-info text-white text-center"
          style={{
            position: 'fixed',
            bottom: 0,
            left: 0,
            width: '100%',
            height: '66px',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
        }}>
          <p style={{ margin: 0, display: 'flex', alignItems: 'center', gap: '20px' }}>
            <strong>&copy; 2024 Gestão de Ensino Especial. Todos os direitos reservados.</strong>
          <a
            href="https://www.facebook.com"
            target="_blank"
            rel="noopener noreferrer"
            style={{ color: 'white', textDecoration: 'none', fontSize: '1.5rem' }} >
          <i className="fab fa-facebook"></i>
          </a>
          <a
            href="https://www.instagram.com"
            target="_blank"
            rel="noopener noreferrer"
            style={{ color: 'white', textDecoration: 'none', fontSize: '1.5rem' }} >
          <i className="fab fa-instagram"></i>
          </a>
          <a
            href="https://wa.me/123456789"
            target="_blank"
            rel="noopener noreferrer"
            style={{ color: 'white', textDecoration: 'none', fontSize: '1.5rem' }} >
          <i className="fab fa-whatsapp"></i>
          </a>
          </p>
        </footer>
      </div>
    </>
  )
}
