import Axios from 'axios';
import NavAdmin from '@/components/NavAdmin';
import TeacherAction from '@/components/TeacherAction';
import Head from 'next/head';
import { useEffect, useState } from 'react';
import MenuUsers from '@/components/MenuUsers';

export default function Teachers() {
  const API_URL = "http://localhost:8080/api/teacher";

  const [teachers, setTeachers] = useState([]); 
  const [filteredTeachers, setFilteredTeachers] = useState([]); 
  const [searchName, setSearchName] = useState(""); 
  const [searchId, setSearchId] = useState(""); 

  useEffect(() => {
    const getAllTeachers = async () => {
      try {
        const response = await Axios.get(API_URL);
        setTeachers(response.data.teachers);
        setFilteredTeachers(response.data.teachers); 
      } catch (error) {
        console.error('Erro ao buscar os professores:', error);
      }
    };

    getAllTeachers();
  }, []);

  const handleSearchByName = (event) => {
    const value = event.target.value;
    setSearchName(value);

    const filtered = teachers.filter(teacher => 
      teacher.name.toLowerCase().includes(value.toLowerCase())
    );
    setFilteredTeachers(filtered);
  };

  const handleSearchById = (event) => {
    const value = event.target.value;
    setSearchId(value);

    const filtered = teachers.filter(teacher => 
      teacher._id.includes(value)
    );
    setFilteredTeachers(filtered);
  };

  return (
    <>
      <Head>
        <title>APP-BC</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div>
        <NavAdmin />
        <MenuUsers />
      </div>

      <div className="d-flex justify-content-center p-2">
        <div className="container">
          <div className="row border-bottom">
            <h3 className="text-center w-100 fw-bold">LISTAGEM DE PROFESSORES CADASTRADOS</h3>
            <div className="d-flex justify-content-center align-items-center" style={{ width: '100%' }}>
              <div className="d-flex gap-3" style={{ width: '100%', maxWidth: '1000px' }}>
                {/* Primeira barra de pesquisa */}
                <div className="input-group search-container" style={{ flex: 1 }}>
                  <input 
                    type="text" 
                    className="form-control search-input" 
                    style={{ maxWidth: '450px', width: '100%', fontSize: '0.9rem', height: '40px' }} 
                    placeholder="Busca por Nome"
                    value={searchName}
                    onChange={handleSearchByName}
                  />
                  <div className="input-group-append" style={{ cursor: 'pointer' }}>
                    <span 
                      className="input-group-text" 
                      style={{
                        height: '40px',
                        display: 'flex',
                        alignItems: 'center',
                        justifyContent: 'center',
                        borderRadius: '0',
                        padding: '0 10px',
                        cursor: 'pointer'
                      }}>
                      <i className="fas fa-search" style={{ fontSize: '1rem' }}></i>
                    </span>
                  </div>
                </div>
                {/* Segunda barra de pesquisa */}
                <div className="input-group search-container" style={{ flex: 1 }}>
                  <input 
                    type="text" 
                    className="form-control search-input" 
                    style={{ maxWidth: '450px', width: '100%', fontSize: '0.9rem', height: '40px' }} 
                    placeholder="Busca por ID"
                    value={searchId}
                    onChange={handleSearchById}
                  />
                  <div className="input-group-append" style={{ cursor: 'pointer' }}>
                    <span 
                      className="input-group-text" 
                      style={{
                        height: '40px',
                        display: 'flex',
                        alignItems: 'center',
                        justifyContent: 'center',
                        borderRadius: '0',
                        padding: '0 10px',
                        cursor: 'pointer'
                      }}>
                      <i className="fas fa-search" style={{ fontSize: '1rem' }}></i>
                    </span>
                  </div>
                </div>
              </div>
            </div>

            <table className="table table-hover">
              <thead>
                <tr>
                  <th scope="col" className="text-center">ID</th>
                  <th scope="col" className="text-center">Nome</th>
                  <th scope="col" className="text-center">Disciplinas</th>
                  <th scope="col" className="text-center">Contato</th>
                  <th scope="col" className="text-center">Ação</th>
                </tr>
              </thead>
              <tbody>
                {filteredTeachers.map(teacher => (
                  <tr key={teacher._id}>
                    <th scope="row" className="text-center">{teacher._id}</th> 
                    <td className="text-center">{teacher.name}</td> 
                    <td className="text-center">{teacher.school_disciplines}</td>
                    <td className="text-center">{teacher.contact}</td> 
                    <td className="text-center">
                      <TeacherAction pid={teacher._id}></TeacherAction> 
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      </div>  
    </>
  );
}
